### ISSUE TITLE
Подсчет гипотетического выйгрыша

### ISSUE THREAD

**Issue by luminousmen** [luminousmen/Master#3]
Предполагаем что популярность блоков распределена по экспоненциальному закону.
В начальный момент все блоки находятся на одном самом медленном типе носителя(SATA) в нашел хранилище. Нужно подсчитать стоимость такого хранилища и время ответа.
Нужно уменьшить время ответа на 10%, 20%, 30%, 50%. Сколько и каких дисков примерно потребуется? Посчитать примерную стоимость хранилища.

**Comment by evlinsky** [comment]
Да. Звучит нормально. Я бы уточнил, что в количестве дисков важно
соотношение в процентах,  а не абсолютное число.

2016-09-01 20:23 GMT+03:00 Kirill <notifications@github.com>:
